### PR TITLE
Fixing color saturation.

### PR DESCRIPTION
**Pull request by Rotfuchs-von-Vulpes**
Hey bro, I thought your theme was really cool but the colors are too strong... what do you think about using colors which are more subtle?

### CODE REVIEW

**Comment by VulpoTheDev** [comment]
Ignore restyle

**Comment by VulpoTheDev** [comment]
I'll take a looksie :3

**Comment by marcusmmmz** [comment]
A screenshot of the theme with some example code would be helpful

**Comment by VulpoTheDev** [comment]
That makes a good improvement to the theme! Thankies

**Comment by VulpoTheDev** [comment]
Some Screenshots of the theme
image
image

**Pull request merged**
